package com.marsboy.vshare.model;
// Generated Dec 24, 2017 7:38:59 PM by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "vshare")
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private byte roleid;
	private String rolename;
	private Set<User> users = new HashSet<User>(0);

	public Role() {
	}

	public Role(byte roleid, String rolename) {
		this.roleid = roleid;
		this.rolename = rolename;
	}

	public Role(byte roleid, String rolename, Set<User> users) {
		this.roleid = roleid;
		this.rolename = rolename;
		this.users = users;
	}

	@Id

	@Column(name = "roleid", unique = true, nullable = false)
	public byte getRoleid() {
		return this.roleid;
	}

	public void setRoleid(byte roleid) {
		this.roleid = roleid;
	}

	@Column(name = "rolename", nullable = false)
	public String getRolename() {
		return this.rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
